      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
C      
C     ABAQUS DIMENSIONS      
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 JSTEP(4)
C
C     USER PARAMETERS - CHANGE NMAXWELL TO ADAPT THE MODEL
C     TO YOUR NUMBER OF MAXWELL ELEMENTS
      PARAMETER(ZERO=0.D0, ONE=1.D0, TWO=2.D0, THREE=3.D0, FOUR=4.D0,
     1 SIX=6.D0, NINE=9.D0, NMAXWELL=23.D0)
C
C     USER DIMENSIONS
      DIMENSION D(3,3),SM0OLD(6), SM1OLD(6), SM2OLD(6), SM3OLD(6),
     1 SM0(6), SM1(6), SM2(6), SM3(6), CE(6,6), PRESTRAN(3), PRESTRESS(3),
     2 K(NMAXWELL), TAU(NMAXWELL), A(NMAXWELL)
C
      REAL*8 M(NMAXWELL), DECSTRESS(6), SMOLD(6,NMAXWELL), SM(6,NMAXWELL),
     1 MSUM, KSUM
C
C     PROPS(1) IS THE RUBBERY YOUNGS MODULUS IN MPA
      K0=PROPS(1)
C     PROPS(2) IS THE POISSONS RATIO
      ENU=PROPS(2)
C     PROPS(3) IS THE GLASS TRANSITION TEMPERATURE IN CELSIUS
      TG=PROPS(3)
C     PROPS(4-6) ARE THE C1 - C3 FOR THE WLF (C1/C2) 
C     AND ARRHENIUS FCT (C3)
      C1=PROPS(4)
      C2=PROPS(5)
      C3=PROPS(6)
C     PROPS(7-9) ARE THE PRESTRAINS FOR DIRECT 4D PRINTING
      PRESTRAN(1)=PROPS(7)
      PRESTRAN(2)=PROPS(8)
      PRESTRAN(3)=PROPS(9)
C     PROPS(10-(END-NMAXWELL)) ARE THE 
C     MAXWELL ELEMENT YOUNGS MODULI IN MPA
      DO K1=1,NMAXWELL
            K(K1)=PROPS(9+K1)
      ENDDO
C     PROPS((END-NMAXWELL)-END) ARE THE 
C     MAXWELL ELEMENT RELAXATION TIMES IN SECONDS
      DO K1=1,NMAXWELL
            TAU(K1)=PROPS(9+NMAXWELL+K1)
      ENDDO
C
C     DEFINE THE TEMPERATURE SCALING COEFFICIENTS ACCORDING
C     TO THE WLF AND ARRHENIUS FUNCTION
C
      T=TEMP+273.15
      T0=TG+273.15
      IF (T .GE. T0) THEN
C           WLF            
            aT=10**(-C1*(T-T0)/(C2+(T-T0)))
      ELSE
C           ARRHENIUS
            aT=10**(C3*(1/T-1/T0))
      ENDIF
C      
C     APPLY SCALING COEFFICIENTS TO THE RELAXATION TIMES      
C
      DO K1=1,NMAXWELL
            TAU(K1)=aT*TAU(K1)
      ENDDO
C
C     DEFINE THE VALUES FOR THE NORMALIZATION
C     FACTOR M(1,....,NMAXWELL)
C
      MSUM = 0.D0
      DO K1=1,NMAXWELL
            M(K1)=TAU(K1)*K(K1)*(1-EXP(-DTIME/TAU(K1)))
     1            /(K0*DTIME)
            MSUM=MSUM+M(K1)
      ENDDO
C
C     DEFINING THE 2D/3D TERMS TO BE USED IN THE STIFFNESS MATRIX
C
      TERM2D=K0/(ONE-ENU*ENU)      
      TERM3D=K0/((1+ENU)*(ONE-TWO*ENU))
C
C     DEFINE SCALING FACTORS FOR DASHPOT DECAY IN MAXWELL ELEMENTS
C
      DO K1=1,NMAXWELL
            A(K1)=EXP(-DTIME/TAU(K1))
      ENDDO
C
C     DEFINE THE ELASTIC STIFFNESS MATRIX FOR THE NEO-HOOKEAN ELEMENT
C
      DO K1=1,NTENS
            DO K2=1,NTENS
                  CE(K1,K2)=0.0D0
            ENDDO
      ENDDO
C
      IF(NSHR.EQ.1) THEN
            CE(1,1)=TERM2D
            CE(2,2)=TERM2D
            CE(3,3)=TERM2D*(ONE-ENU)/TWO
            CE(1,2)=TERM2D*ENU
            CE(2,1)=TERM2D*ENU
      END IF
C
C     ON INITIALIZATION IMPART RESIDUAL STRESS ON STATE VARIABLES
C     BASED ON PRINT PARAMETERS. THE RESIDUAL STRESS IS FIRST
C     IMPARTED ON THE LINEAR-ELASTIC ELEMENT, MAXWELL ELEMENTS
C     ARE THEN BALANCED SUCH THAT RESULTING STRESS IS ZERO
C
      KSUM = 0.D0
      IF (TIME(2).EQ.ZERO .AND. KINC.LE.ONE) then
            IF(NSHR.EQ.1) THEN
                  PRESTRESS(1)=CE(1,1)*PRESTRAN(1)+CE(1,2)*PRESTRAN(2)
                  PRESTRESS(2)=CE(2,1)*PRESTRAN(1)+CE(2,2)*PRESTRAN(2)
                  PRESTRESS(3)=CE(3,3)*PRESTRAN(3)
            END IF
            SM0OLD(1)=PRESTRESS(1)
            SM0OLD(2)=PRESTRESS(2)
            SM0OLD(3)=PRESTRESS(3)
            
            DO K1=1,NMAXWELL
                KSUM=KSUM+K(K1)
            ENDDO

            DO K1=1,NMAXWELL
                DO K2=1,NTENS
                      SMOLD(K2,K1)=-PRESTRESS(K2)*K(K1)/KSUM
                ENDDO
            ENDDO
      ELSE
C           FETCH RESIDUAL STRESS FOR LINEAR ELASTIC ELEMENT FROM PREVIOUS
C           ITERATION THAT WAS SAVED IN THE STATE VARIABLE
            DO I=1,NTENS
                  SM0OLD(I)=STATEV(I)
            ENDDO
C           FETCH RESIDUAL STRESSES FOR MAXWELL ELEMENTS FROM PREVIOUS
C           ITERATION THAT WERE SAVED IN STATE VARIABLES
            DO K1=1,NMAXWELL
                DO K2=1,NTENS
                      SMOLD(K2,K1)=STATEV(K2+K1*6)
                ENDDO
            ENDDO
      END IF
C
C     DEFINING STRESS AND STRAIN RELATION
C
      IF(NSHR.EQ.1) THEN
      DO K1=1,NTENS
            DECSTRESS(K1)=0.D0
      ENDDO
      DO K1=1,NTENS
            DO K2=1,NMAXWELL
                  DECSTRESS(K1)=DECSTRESS(K1)+A(K2)*SMOLD(K1,K2)
            ENDDO
      ENDDO
      STRESS(1)=SM0OLD(1)+
     1          +DECSTRESS(1)
     2          +(1+MSUM)
     3          *(CE(1,1)*DSTRAN(1)+CE(1,2)*DSTRAN(2))
      STRESS(2)=SM0OLD(2)+
     1          +DECSTRESS(2)
     2          +(1+MSUM)
     3          *(CE(2,1)*DSTRAN(1)+CE(2,2)*DSTRAN(2))
      STRESS(3)=SM0OLD(3)+
     1          +DECSTRESS(3)
     2          +(1+MSUM)*(CE(3,3)*DSTRAN(3))
      END IF
C
C     CALCULATE RESIDUAL STRESSES FOR NEXT STEP
C
      IF(NSHR.EQ.1) THEN
      SM0(1)=SM0OLD(1)+(CE(1,1)*DSTRAN(1)+CE(1,2)*DSTRAN(2))
      SM0(2)=SM0OLD(2)+(CE(2,1)*DSTRAN(1)+CE(2,2)*DSTRAN(2))
      SM0(3)=SM0OLD(3)+(CE(3,3)*DSTRAN(3))
      
      DO K1=1,NMAXWELL
            SM(1,K1)=A(K1)*SMOLD(1,K1)+M(K1)
     1               *(CE(1,1)*DSTRAN(1)+CE(1,2)*DSTRAN(2))
            SM(2,K1)=A(K1)*SMOLD(2,K1)+M(K1)
     1               *(CE(2,1)*DSTRAN(1)+CE(2,2)*DSTRAN(2))
            SM(3,K1)=A(K1)*SMOLD(3,K1)+M(K1)
     1               *(CE(3,3)*DSTRAN(3))
      ENDDO
      END IF
C
C     UPDATE STATE VARIABLES THAT ARE PASSED TO ABAQUS
C
      DO K1=1,NTENS
            STATEV(K1)=SM0(K1)
      ENDDO
      DO K1=1,NMAXWELL
            DO K2=1,NTENS
                  STATEV(K2+K1*6)=SM(K2,K1)
            ENDDO
      ENDDO
C
C     CREATE JACCOBIAN MATRIX
C
      DO K1 = 1,NTENS
            DO K2= 1, NTENS
                  DDSDDE(K2,K1) = 0.D0
            ENDDO
      ENDDO
C
      DO K1=1,NTENS
            DO K2=1,NTENS
                  DDSDDE(K1,K2)=(1+MSUM)*CE(K1,K2)
            ENDDO
      ENDDO
C
C     CHANGE IN SPECIFIC ELASTIC STRAIN ENERGY
C
      DEE = 0.
      DO K1=1,NDI
            TERM1 = 0.
            TERM2 = 0.
            DO K2=1,NDI
                  TERM1 = TERM1 + CE(K1,K2)*STRAN(K2)
                  TERM2 = TERM2 + CE(K1,K2)*DSTRAN(K2)
            END DO
            DEE = DEE + (TERM1+.5*TERM2)*DSTRAN(K1)
      END DO
      I1 = NDI
      DO K1=1,NSHR
            I1 = I1+1
            DEE = DEE + K0*(STRAN(I1)+.5*DSTRAN(I1))*DSTRAN(I1)
      END DO
      SSE = SSE + DEE
C
      RETURN
      END