



  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1392
     no. of nonzeroes in lower triangle of a =           12422
     no. of nonzeroes in the factor l        =           72256
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =              87
     maximum order of a front matrix         =             109
     maximum size of a front matrix          =            5995
     maximum size of a front trapezoid       =            5995
     METIS reordering method used 
     no. of floating point ops for factor    =      3.1028D+06
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =            1352
     number of negative pivots               =              40
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =              31
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               6
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               1
     number of cores used                    =               1
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000559
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000902

     no input or output performed

  Total Solver Memory allocated              =       11.648 MB
