



  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            2988
     no. of nonzeroes in lower triangle of a =           27281
     no. of nonzeroes in the factor l        =          191203
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =             194
     maximum order of a front matrix         =             144
     maximum size of a front matrix          =           10440
     maximum size of a front trapezoid       =            8256
     METIS reordering method used 
     no. of floating point ops for factor    =      1.1114D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =            2988
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               1
     number of cores used                    =               1
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.000676
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001326

     no input or output performed

  Total Solver Memory allocated              =        3.329 MB
