



  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1352
     no. of nonzeroes in lower triangle of a =           12105
     no. of nonzeroes in the factor l        =           70390
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =              83
     maximum order of a front matrix         =             116
     maximum size of a front matrix          =            6786
     maximum size of a front trapezoid       =            6786
     METIS reordering method used 
     no. of floating point ops for factor    =      3.0898D+06
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =            1352
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               1
     number of cores used                    =               1
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000263
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000572

     no input or output performed

  Total Solver Memory allocated              =        1.373 MB
