"""Human-appraised source notes plus verified metadata; no material values adopted."""
from pathlib import Path
import json,re,html
ROOT=Path(__file__).resolve().parents[1]
NR='Not extracted from accessible evidence; do not assume absent'
FIELDS=['PLA grade','geometry','print condition','annealing temperature','holding time','support/constraint','mechanical data','dimensional data','thermal data','constitutive properties','simulation method','validation usefulness','limitations','relevance','source locator']
NOTES={}
def add(key,**kw): NOTES[key]=kw
add('Bute2024',grade='Black Devil Design PLA',geometry='Cubes; size and layer thickness varied',printing='210 °C nozzle; 70 °C bed; 20 mm s⁻¹; unidirectional lines; 100% infill (§2.1)',temperature='TMA cycles 30–140 °C (§2.2); not an isothermal furnace prescription',holding='Heating rate 1 °C min⁻¹; no hold adopted',support='TMA probe; printing-bed boundary in FE',mechanical='Simulated printing residual stress; correlation with measured irreversible strain',dimensional='Directional irreversible strain and second-cycle expansion',thermal='TMA thermal histories and expansion coefficients',constitutive='Thermoelastic printing model; distinguish recovery from reversible CTE',simulation='ANSYS transient deposition with progressive element activation',validation='Candidate directional recovery benchmark; no fixture-stress validation',limitations='Stress–strain correlation is not a validated contact-annealing prediction',relevance='Direct precedent for ANSYS, residual stress and irreversible thermal strain',locator='§§2.1–2.3; §3; Figs 4–5, 9 onward; pp. 218–224')
add('Wijnen2018',grade='PLA; grade not extracted',geometry='Thin vertical walls',printing='FFF without heated chamber',temperature='50 °C and 90 °C discussed (abstract)',support='Printing substrate; annealing fixture not established in reviewed abstract',mechanical='No stress measurement established by reviewed abstract',dimensional='Curvature validation; signed horizontal and vertical annealing response',thermal='Thermal measurements used for calibration; crystallinity discussion',constitutive='Thermal deformation model',simulation='Modified printing-warpage model',validation='Candidate free curvature and directional annealing comparison',limitations='Primary repository abstract reviewed; full protocol needed before extraction',relevance='Warpage modeling and annealing deformation already combined',locator='Author repository abstract; DOI-linked journal abstract')
add('Trofimov2022',grade='PLA; grade not extracted',geometry='Regular plate and bridge-like structure (Fig. 4)',printing='Measured process histories; G-code-driven deposition',temperature='Printing thermal cycle; post-print annealing not the target',holding='Not applicable to a dedicated annealing hold',support='Printing bed; boundary assumptions discussed in §4',mechanical='Predicted distortion and thermo-mechanical response',dimensional='Optical 3D scan comparison',thermal='Infrared thermography comparison',constitutive='Temperature-dependent mechanical and thermal relations',simulation='Sequential thermal–mechanical FE; progressive activation',validation='Thermal and free-warpage methods; cannot validate annealing fixture contact',limitations='Some distortion comparisons qualitative; printing history differs',relevance='Coupling and stepwise physical validation are established',locator='§§2–4; Fig. 4; discussion following Fig. 11')
add('Laminate2025',grade='Prusament PLA; Extrudr PETG as second material',geometry='Bilayers, bending/twisting examples and wave spring',printing='Explicit laminate orientation and programmed print pre-strain',temperature='PLA characterization 23–85 °C (§2.2.1); activation cycles',holding='No furnace annealing hold adopted',support='Activation/mechanical test boundaries; no clearance-controlled annealing study identified',mechanical='DMA and response-force benchmarks',dimensional='Shape deployment benchmarks',thermal='Frequency sweeps and activation temperatures',constitutive='Modified generalized Maxwell; Prony; WLF above glass transition, Arrhenius below',simulation='Abaqus UMAT with laminate shell elements',validation='Constitutive/recovery method candidate; independently reserve compatible observations',limitations='Programmed 4D structures; calibration range does not cover all proposed temperatures',relevance='Temperature-dependent recovery and viscoelastic FE are not novel',locator='§§2.1–2.2; benchmark sections; supplementary parameters referenced, not adopted')
add('Prediction2023',grade='PLA shape-memory filament; grade not extracted',geometry='Dog-bone, TMA cubes and DMA bars',printing='Five printing variables studied',temperature='TMA 0–90 °C then 0–150 °C; DMA to 150 °C (§§2.4–2.5)',holding='TMA initial 0 °C isotherm 10 min; not an annealing dwell recommendation',support='Mechanical/DMA grips and TMA probe',mechanical='Tensile, DMA and shape-memory cycles',dimensional='Directional TMA and recovery',thermal='DSC, TMA, DMA',constitutive='Mooney–Rivlin plus Prony-series viscoelasticity and temperature shift',simulation='ANSYS Workbench material-response simulation',validation='Potential constituent benchmark; fitted curves are calibration, not independent validation',limitations='Finite-strain shape-memory tests differ from spontaneous constrained annealing',relevance='ANSYS with Prony and shifting already demonstrated',locator='§§2.3–2.7, especially §2.7.2; results')
add('Process2025',grade='PLA; grade not extracted',geometry='Thin printed samples',printing='G-code-to-event-series activation',temperature='Printing, cooling and detachment; not furnace annealing',holding='Not applicable to dedicated annealing hold',support='Build-platform adhesion followed by detachment',mechanical='Residual stress and deformation predictions',dimensional='Vertical displacement validation',thermal='Transient FE; temperature-dependent tabulated properties',constitutive='Thermo-mechanical properties drawn from prior sources',simulation='Abaqus 2020; thermal field drives mechanical step',validation='Detachment and boundary-condition benchmark methodology',limitations='Borrowed properties require original-source audit; no opposed fixture clearance',relevance='Release-stage modeling is not new by itself',locator='Model-development sections; Table 3; §3.1 and validation discussion')
add('Mould2022',grade='Ultimaker Pearl White PLA; ABS comparator',geometry='80 × 10 × 4 mm bars (§2.1)',printing='215 °C nozzle; 60 °C bed; 60 mm s⁻¹; 0.2 mm layers; 0° lines (§2.1)',temperature='PLA: 63, 75, 86, 98, 109, 132, 155 °C (Tables 2–3)',holding='120 min; 10 °C min⁻¹ ramp; cool before unpacking (§2.2)',support='Dry alumina powder mould versus unsupported',mechanical='Flexural tests',dimensional='Signed three-direction changes and mould effectiveness',thermal='Furnace schedule; no transferable contact conductance extracted',constitutive='No FE constitutive identification',simulation='Polynomial response descriptions, not contact FE',validation='Support comparison context; numerical extraction blocked for inconsistent last Table 7 entry',limitations='Table 7 says 240 °C for final PLA row while Tables 2–3 say 155 °C; no silent repair',relevance='Constrained annealing and dimensional support efficacy already studied',locator='§§2.1–2.4; Tables 1–3 and 7; §3')
add('Wijnbergen2021',grade='Tough PLA',geometry='Tensile specimens and rings; prosthetic-socket application',printing='Longitudinal and transverse orientations',support='Oven, sand, water and glycerol methods',mechanical='Tensile strength comparison',dimensional='Ring dimensional change',thermal='Annealing medium comparison',simulation='Experimental comparison; no FE identified in accessible evidence',validation='Medium/support effects only until grade and thermal protocol match',limitations='Tough formulation differs from neat PLA; full protocol not acquired',relevance='Support media and directional mechanical response are established',locator='Publisher abstract and accessible article excerpts')
add('HighHeat2026',grade='Ingeo 3D850',geometry='Standardized specimens; details not extracted',printing='190–260 °C nozzle (publisher abstract)',temperature='100 °C (abstract)',holding='4 h (abstract)',support='Not established from accessible primary abstract',mechanical='Tensile response',dimensional='Height, width and length accuracy',thermal='Annealed/non-annealed treatment',simulation='Machine-learning prediction; not fixture-contact FE',validation='High-heat grade comparison only; protocol acquisition required',limitations='Online 2025, issue 2026; do not assume sand restraint from secondary descriptions',relevance='Joint dimensional/mechanical annealing prediction is established',locator='Publisher abstract; online publication 17 Nov 2025, issue Feb 2026')
add('Multiscale2026',grade='PLA; grade not extracted',geometry='Printed tensile structures',printing='Raster orientations 0°, 45°, 90° (abstract)',support='Tensile boundary conditions; annealing fixture not established in abstract',mechanical='Tensile stiffness, strength and elongation',dimensional='Released annealing warpage not established in abstract',thermal='Annealed/non-annealed comparison and DSC interpretation',constitutive='Homogenized anisotropic model',simulation='Multiscale FE and composite desirability optimization',validation='Tensile benchmark; independence of fitted/validation data requires full-text appraisal',limitations='Publisher early unedited article; abstract does not establish transient contact physics',relevance='Direct counterexample to novelty based on annealing + FE + multi-objective optimization',locator='Publisher abstract and publication history, 25 June 2026; not AI-generated summary')
add('SCF2023',grade='Short-carbon-fibre-reinforced PLA',geometry='Square and circular tubes',printing='FFF deposition with active elements',support='Printing bed',mechanical='Computed residual stresses',dimensional='Computed warpage',thermal='DSC and temperature-dependent properties',constitutive='Thermoelasticity and Nakamura crystallization kinetics',simulation='MSC Digimat-AM multiphysics model',validation='Method precedent; composite properties not transferable to neat PLA',limitations='Some model parameters fitted to crystallinity; calibration cannot double as validation',relevance='Thermal–mechanical–crystallization coupling already exists',locator='Primary article §§3.1–3.2; Fig. 4; Table 1')
add('Orthotropic2024',grade='PLA',geometry='Directional mechanical specimens',printing='Raster and road spacing varied',mechanical='Directional elastic and yield response',constitutive='Orthotropic compliance and Hill-type yield modeling',simulation='Analytical/numerical orthotropic mechanical representation',validation='Candidate orientation-dependent mechanics; not an annealing-range law',limitations='Road air gap is distinct from fixture clearance',relevance='FFF orthotropy is established and must be grade/architecture-specific',locator='Publisher/author accepted article abstract and mechanical-model description')
add('Pantani2010',grade='Virgin and processed PLA',thermal='Crystallization kinetics under processing histories',constitutive='Kinetic modeling candidates',validation='Potential DSC calibration; not independent printed dimensional validation',limitations='Processing history and grade must match',relevance='Cold/melt history cannot be collapsed to a universal kinetics law',locator='Publisher abstract')
add('Nucleation2011',grade='PLA',thermal='Nucleation and crystallization kinetics',constitutive='Crystallization kinetics',validation='Mechanism and kinetic-source candidate',limitations='No printed fixture response established in abstract',relevance='Crystallization modeling itself is established',locator='Publisher abstract')
add('Kinetics2025',grade='PLA filament; exact grade not extracted',thermal='Cold versus melt crystallization and thermal history',constitutive='Filament-specific kinetics',validation='Potential kinetics calibration, pending full parameter extraction',limitations='No fixture clearance/contact validation in accessible abstract',relevance='FFF-filament crystallization is already modeled',locator='Publisher abstract')
add('Deformation2025',grade='Amorphous PLA',temperature='70 °C in accessible primary abstract',mechanical='Multi-step tensile deformation',thermal='Crystal evolution with deformation and annealing',constitutive='Stress/deformation–crystallization interaction context',validation='Mechanism only; not free FFF annealing validation',limitations='Online 2024, issue 2025; deformation protocol differs',relevance='Stress-independent kinetics must be justified',locator='Publisher abstract')
add('Viscoplastic2017',grade='PLA; not established as FFF',mechanical='Temperature-dependent loading/unloading and time dependence',constitutive='Viscoelastic–viscoplastic response',validation='Nonlinearity context; no transferable parameter set extracted',limitations='Online 2016, issue 2017; bulk response cannot replace printed law',relevance='A linear Prony law may be inadequate under large restraint',locator='Publisher abstract')
add('Relaxation2022',grade='SUNLU PLA plus',geometry='120 × 6 × 3 mm rectangular specimens (§2.1)',printing='210 °C nozzle; 50 °C bed; 60 mm s⁻¹; 0.1 mm layer (§2.1)',holding='500 s relaxation observation, not annealing dwell (§2.1)',support='Tensile grips; imposed strain',mechanical='Stress relaxation with infill-direction and conditioning effects',constitutive='Maxwell, standard linear solid and Findley fits',simulation='Analytical curve fitting',validation='Relaxation-law appraisal; independent dataset reservation required',limitations='Short relaxation tests do not establish an annealing-range WLF master curve',relevance='Relaxation is measured in FFF PLA, not a proposed discovery',locator='§§2.1–2.2; results')
add('Kahya2025',grade='PLA',mechanical='Annealing-dependent mechanical response',thermal='Temperature/time optimization',simulation='Experimental optimization study',validation='Treatment-context source; no fixture-stress validation',limitations='Reported optimum is material/test-specific',relevance='Optimizing annealing temperature and time is not novel',locator='Publisher abstract')
add('Encapsulation2025',grade='BASF/Forward AM Ultrafuse PLA Tough',geometry='Hollow cylinders, bars, curved beams and application geometry',support='Salt and RTV silicone encapsulation',mechanical='Bending/thermal creep and application performance',dimensional='Dimensional precision across geometries',thermal='Thermal processing and sterilization assessment',simulation='Experimental post-processing comparison',validation='Support-method context; not opposed-gap validation',limitations='Tough PLA and encapsulation media differ; no adopted contact law',relevance='Encapsulation and dimensional preservation already investigated',locator='§§2.1–2.2; subsequent treatment and results sections')
add('Salt2022',support='Salt-assisted annealing/remelting',mechanical='Tensile response',simulation='Experimental thermal post-processing',validation='Context only for sub-melting study',limitations='Remelting is outside present scope',relevance='Salt restraint is not novel',locator='Publisher abstract')
add('Moulds2022',support='Annealing in moulds',mechanical='Mechanical-property comparisons',simulation='Experimental mould-supported processing',validation='Support precedent; protocol compatibility required',limitations='Mould behavior cannot be replaced by ideal fixed faces',relevance='Mechanical support during annealing is prior art',locator='Publisher abstract')
add('Wach2018',grade='FDM PLA',mechanical='Annealing-dependent mechanical performance',thermal='Thermal treatment and morphology',validation='Background; grade/architecture matching required',limitations='Mechanical enhancement does not validate residual-stress predictions',relevance='Thermal post-treatment of FDM PLA is established',locator='Publisher abstract')
add('Benwood2018',grade='PLA',mechanical='Impact response and heat resistance',thermal='Processing–structure relationships',validation='Mechanistic background',limitations='Mechanical and thermal endpoints differ from released fixture warpage',relevance='Processing, morphology and properties are linked',locator='Publisher abstract')
add('Windheim2021',grade='Printed PLA',mechanical='Tensile strength and interlayer adhesion',thermal='Crystallinity considered',validation='Mechanistic context; no selected calibration data',limitations='Porosity and bonding confound a crystallinity-only strength law',relevance='Crystallinity alone cannot justify strength improvement',locator='Publisher abstract')
add('Bonding2024',grade='Printed PLA',mechanical='Heat-treatment mechanical response',thermal='Crystallization–interlayer-bonding competition',validation='Mechanistic context',limitations='No fixture-specific stress validation established',relevance='Annealing need not improve every property',locator='Publisher abstract')
add('Stojkovic2023',grade='FDM printed polymer; PLA study context',printing='Layer height varied',mechanical='Tensile strength',dimensional='Dimensional accuracy',thermal='Annealing temperature and time varied',simulation='Experimental factorial assessment',validation='Candidate dimensional data after compatibility audit',limitations='Experimental statistics do not transfer to repeated deterministic FE runs',relevance='Joint thermal/process factor studies already exist',locator='Publisher abstract; stage-1 verified source record')
add('Butt2020',grade='Several FFF thermoplastics including PLA',mechanical='Annealing-dependent mechanical tests',thermal='Thermal post-treatment',simulation='Experimental comparison',validation='Context until matching grade and protocol established',limitations='Cross-polymer comparisons cannot supply a universal PLA law',relevance='Annealing of FFF thermoplastics is established',locator='Publisher abstract; stage-1 verified source record')
add('Derringer1980',grade='Not applicable: statistical methodology',simulation='Desirability functions for several responses',validation='Optimization method only, not physical validation',limitations='Weights and desirability bounds are analyst choices',relevance='Multi-response desirability is not new',locator='Original journal article, pp. 214–219; stage-1 source verification')
add('WLF1955',grade='Amorphous polymers/glass-forming liquids; not FFF-specific',constitutive='Temperature–relaxation shift relationship',validation='Foundational method, not PLA parameter evidence',limitations='Do not assume universal shift constants or thermorheological simplicity',relevance='WLF shifting is established',locator='Original JACS article pp. 3701–3707; publisher bibliographic record')
add('Heat2023',grade='FFF polymer; exact grade not extracted',geometry='Printed infill geometries',thermal='Transient heat transfer and thermal validation',simulation='Hybrid activation and error-based mesh coarsening',validation='Thermal verification/validation methodology',limitations='No fixture interface conductance inferred from thermal agreement',relevance='Efficient transient thermal FE already developed',locator='Publisher abstract')
add('Phase2025',grade='PLA layers',thermal='Thermal and morphological evolution',constitutive='Effective elastic response informed by phase-field morphology',simulation='Phase-field modeling',validation='Multiscale mechanism context',limitations='Online 2024, issue 2025; not a fixture-contact validation dataset',relevance='Morphology–thermal–mechanical coupling is established',locator='Publisher abstract')
add('Grades2026',grade='Injection-moulded PLA grades',thermal='Crystallinity and secondary shrinkage',mechanical='Mechanical performance',dimensional='Dimensional stability',validation='Mechanism context only; not FFF validation',limitations='Online 5 July 2026 included; October 2026 issue date is later than cutoff',relevance='Grade-specific annealing trade-offs remain important',locator='Publisher metadata and author-repository abstract')
add('PINN2026',grade='Recycled PLA',temperature='75 °C (§3)',holding='3 h (§3)',mechanical='Strength, stiffness and ductility predictions',thermal='Crystallinity/annealing state as learning constraints',simulation='Physics-informed neural network and Bayesian/Pareto optimization',validation='Published data reuse; examine sample grouping before trusting independence',limitations='Thermo-constrained refers to learning constraints, not a mechanical fixture; load-curve records are not independent specimens',relevance='Physics-guided PLA optimization is already reported',locator='Publisher abstract and §3 methods; no accuracy values adopted')
MAP={'grade':'PLA grade','geometry':'geometry','printing':'print condition','temperature':'annealing temperature','holding':'holding time','support':'support/constraint','mechanical':'mechanical data','dimensional':'dimensional data','thermal':'thermal data','constitutive':'constitutive properties','simulation':'simulation method','validation':'validation usefulness','limitations':'limitations','relevance':'relevance','locator':'source locator'}
def main():
 raw=json.loads((ROOT/'literature/doi_verification.json').read_text(encoding='utf-8'))
 acquired={x['key']:x for x in json.loads((ROOT/'literature/acquisition_manifest.json').read_text())}
 rows=[]
 for r in raw:
  assert 'error' not in r,r
  r['journal']=html.unescape(r['journal'])
  r['title']=' '.join(html.unescape(re.sub('<[^>]+>','',r['title'])).split())
  # Use issue year in bibliography while preserving all online dates.
  r['year']=r['publication_dates'].get('published-print',r['publication_dates']['published'])[0][0]
  r.update({f:NR for f in FIELDS});r.update({MAP[k]:v for k,v in NOTES[r['key']].items()})
  r['source URL']=acquired.get(r['key'],{}).get('url','https://doi.org/'+r['doi'])
  r['access level']='Full text retrieved; targeted methods/results appraisal' if r['key'] in acquired else 'Primary abstract/excerpts; no full protocol extraction'
  r['adoption status']='Literature only; no solver input or validation datum adopted'
  rows.append(r)
 (ROOT/'literature/literature_matrix.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 bib=[]
 for r in rows:
  fields={'author':r['authors'].replace('; ',' and '),'title':'{'+r['title']+'}','journal':r['journal'],'year':str(r['year']),'volume':r['volume'],'number':r['issue'],'pages':r['pages'],'doi':r['doi'],'url':'https://doi.org/'+r['doi']}
  bib.append('@article{'+r['key']+',\n'+',\n'.join('  '+k+' = {'+str(v).replace('&',r'\&')+'}' for k,v in fields.items() if v)+'\n}')
 # Previously verified ASTM remains a standard, not a peer-reviewed matrix study.
 old=json.loads((ROOT/'data/literature/verified_sources.json').read_text(encoding='utf-8'))
 std=next(x for x in old if x['id']==3)
 bib.append('@misc{ASTM2023,\n  author = {{ASTM International}},\n  title = {{ASTM F3489-23: '+'Standard Guide for Additive Manufacturing of Polymers — Material Extrusion — Recommendation for Material Handling and Evaluation of Static Mechanical Properties'.replace('&',r'\&')+'}},\n  year = {2023},\n  doi = {'+std['doi']+'}\n}')
 (ROOT/'literature/references.bib').write_text('\n\n'.join(bib)+'\n',encoding='utf-8')
 print(f'{len(rows)} verified and appraised journal records; ASTM separately retained')
if __name__=='__main__':main()
