



  Performance statistics for DSP solver: icalls =    827

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            4080
     no. of nonzeroes in lower triangle of a =           37124
     no. of nonzeroes in the factor l        =          239784
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =             285
     maximum order of a front matrix         =             116
     maximum size of a front matrix          =            6786
     maximum size of a front trapezoid       =            6191
     METIS reordering method used 
     no. of floating point ops for factor    =      1.1790D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =               0
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               1
     number of cores used                    =               1
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000
     time (cpu & wall) for numeric solve     =        0.015625        0.000916
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     no input or output performed

  Total Solver Memory allocated              =        3.696 MB
